[package]
name = "protobuf-test"
version = "0.1.0"
authors = ["Lars Kroll <lkroll@kth.se>"]
edition = "2018"
publish = false

[dependencies]
kompact = { path = "../../core/", features = ["protobuf"]}
protobuf = "2.10.1"
bytes = "0.5.2"

[build-dependencies]
protoc-rust = "2.10.1"
