language: rust
rust:
  - nightly
  - stable
  - beta
cache: cargo
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cd core
  - ./test-feature-matrix.sh

# make sure protobuf library and mdbook are installed for build to succeed
before_install:
  - ./travis_install_protobuf.sh
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - cargo install-update -a

jobs:
  include:
    - stage: deploy
      name: "Github Release"
      script: mdbook build docs
      deploy:
        provider: pages
        cleanup: true
        token: $GITHUB_TOKEN
        local_dir: docs/book/html
        keep_history: false
        on:
          branch: master
