# make sure protobuf library and mdbook are installed for build to succeed
before_install:
  - ./travis_install_protobuf.sh
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - (test -x $HOME/.cargo/bin/mdbook-linkcheck || cargo install mdbook-linkcheck)
  - cargo install-update -a

language: rust
rust:
  - nightly
  - stable
jobs:
  include:
    - stage: test
      name: "Build and test root"
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
    - stage: test-features
      name: "Test feature matrix"
      script:
        - cd core
        - ./test-feature-matrix.sh
    - stage: deploy
      name: "Github Release"
      script: mdbook build docs
      deploy:
        provider: pages
        edge: true
        cleanup: false
        token: $GITHUB_TOKEN
        local_dir: docs/book/html
        keep_history: false
        on:
          branch: master
