[package]
name = "kompics"
version = "0.1.0"
authors = ["Lars Kroll <lkroll@kth.se>"]

[dependencies]
#futures = "0.1"
#futures-cpupool = "0.1"
component-definition-derive = { path = "../macros/component-definition-derive/" }
threadpool = "1.7.1"
crossbeam = "0.3.0"
synchronoise = "0.3.0"
uuid = { version = "0.4", features = ["serde", "v4"] }
time = "0.1"
as_num = "0.2.3"