[package]
name = "kompics"
version = "0.1.0"
authors = ["Lars Kroll <lkroll@kth.se>"]

[dependencies]
log = "0.3"
component-definition-derive = { path = "../macros/component-definition-derive/" }
executors = "0.3"
crossbeam = "0.3"
synchronoise = "0.4"
uuid = { version = "0.4", features = ["serde", "v4"] }
time = "0.1"
as_num = "0.2"
num_cpus = "1.0"

[dev-dependencies]
env_logger = "0.4"