[package]
name = "kompics"
version = "0.3.0"
authors = ["Lars Kroll <lkroll@kth.se>"]

[dependencies]
log = "0.3"
component-definition-derive = { path = "../macros/component-definition-derive/" }
actor-derive = { path = "../macros/actor-derive/" }
executors = "0.4"
crossbeam = "0.3"
crossbeam-channel = "0.2"
synchronoise = "0.4"
uuid = { version = "0.4", features = ["serde", "v4"] }
time = "0.1"
as_num = "0.2"
num_cpus = "1.0"
oncemutex = "0.1.1"
serde = "1.0"
sequence_trie = "0.3.5"
slog = {version = "2.2", features = ["max_level_debug", "release_max_level_info"]}
slog-async = "2.3"
slog-term = "2.4"

# Network-specific
bytes = "0.4.8"
futures = "0.1.2"
tokio = "0.1.7"
tokio-retry = "0.2.0"

[dependencies.spaniel]
git = "https://github.com/jarlopez/spaniel"
branch = "master"

[dependencies.bitfields]
git = "https://github.com/jarlopez/bitfields-rs"
branch = "master"


[dev-dependencies]
#env_logger = "0.4"
